name: Foundry CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  forge-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run forge install
        run: forge install

      - name: Run forge build
        run: forge build

      - name: Run tests
        run: forge test -vvv

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run forge install
        run: forge install

      - name: Check if forge fmt was run
        run: forge fmt --check
